// <auto-generated />
using FocusHereApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusHereApi.Migrations
{
    [DbContext(typeof(FocusHereApiContext))]
    [Migration("20240310032634_addCanvasIdtoCourses")]
    partial class addCanvasIdtoCourses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FocusHereApi.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CanvasId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("Teacher")
                        .HasColumnType("longtext");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CanvasId = 0,
                            Name = "Math",
                            Period = 1,
                            Teacher = "Mr. Smith"
                        },
                        new
                        {
                            CourseId = 2,
                            CanvasId = 0,
                            Name = "Science",
                            Period = 2,
                            Teacher = "Mrs. Johnson"
                        },
                        new
                        {
                            CourseId = 3,
                            CanvasId = 0,
                            Name = "History",
                            Period = 3,
                            Teacher = "Mr. Johnson"
                        });
                });

            modelBuilder.Entity("FocusHereApi.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SchoolName")
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            GradeLevel = 12,
                            Name = "John Doe",
                            SchoolName = "Springfield High School"
                        },
                        new
                        {
                            StudentId = 2,
                            GradeLevel = 11,
                            Name = "Jane Doe",
                            SchoolName = "Springfield High School"
                        },
                        new
                        {
                            StudentId = 3,
                            GradeLevel = 10,
                            Name = "Jim Doe",
                            SchoolName = "Springfield High School"
                        },
                        new
                        {
                            StudentId = 4,
                            GradeLevel = 9,
                            Name = "Jill Doe",
                            SchoolName = "Springfield High School"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
